changes

diff --git a/.github/workflows/pr-check.yml b/.github/workflows/pr-check.yml
--- a/.github/workflows/pr-check.yml
+++ b/.github/workflows/pr-check.yml
@@ -29,4 +29,6 @@ jobs:
 
     - name: Check Terraform formatting
       if: steps.fmt.outcome == 'failure'
-      run: exit 1
+      run: |
+        echo "Terraform formatting check failed"
+        exit 1
